### PR TITLE
Implement windows stack tracing

### PR DESCRIPTION
**Pull request by implausible**

### CODE REVIEW

**Comment by No9** [comment]
Thanks very much for this I'll take a look tomorrow

**Comment by tbranyen** [comment]
Wow awesome!

**Comment by implausible** [comment]
Perhaps the major concerns with windows stack traces is that we should make people aware that in order to resolve names for windows stack traces the pdb files associated with each node module or executable must be included in the project.

**Comment by No9** [comment]
LGTM :+1: 
@raymondfeng Do you want to give it the once over or should I just get on and push it?

**Comment by No9** [comment]
Now this has landed and we have windows support also suggesting we semver the release and go for 1.0.0? @raymondfeng

**Comment by Drillyus** [comment]
Hi , when the marge  will be doing ?

**Comment by No9** [comment]
@Drillyus OK I think no news is good news from @raymondfeng 
Will push today.

**Comment by Drillyus** [comment]
ok thanks , i need that to finalize a Node module :)

**Comment by No9** [comment]
@Drillyus that is now in NPM as 1.0.0 as we are using semantic versioning from this point on

**Comment by Drillyus** [comment]
Thanks you :)

**Pull request merged**
