### PR TITLE
Don't use v8-debug.h

### PR DESCRIPTION
**Pull request by tcolgate**

### CODE REVIEW

**Comment by Djiit** [comment]
Hi @ddopson , could you please merge this as this can be a rather blocking issue with Node 10 ?

**Comment by No9** [comment]
Thanks for the contribution
I’ll take a look later but it might stretch to the weekend before it’s pushed

**Comment by ddopson** [comment]
Would you like to be a maintainer for this package? I'm not doing much in
Node these days...

**Comment by Djiit** [comment]
Hi there ! Do you need any help to merge this ?

**Comment by ddopson** [comment]
@Djiit - I actually did! For a while, I had lost my GitHub password. Fixed now.

Seriously, I don't even have a NodeJS environment installed, so if anybody wants to step up and be a more responsible maintainer for this package, it's a really low bar right now...

**Comment by dy-dx** [comment]
@No9 @ddopson Thank you! Could you publish a new version to npm?

**Comment by ddopson** [comment]
I'd like to. First I need to *install* npm, and figure out which password I
used.

Bonus points for anybody who finds an automated build system. (seriously,
it should just auto-cut versions for every push to GitHub that passes
tests!)

**Comment by ddopson** [comment]
Probably this?: https://docs.travis-ci.com/user/deployment/npm/

**Comment by ddopson** [comment]
Is anyone willing to step up and work with me to get this module tested /
auto-deployed / become a maintainer?

  --- Dave

**Comment by No9** [comment]
Published as 1.0.1 as it's a backward compatible bug fix not new functionality

**Pull request merged**
